# Generated by Django 3.2.6 on 2022-06-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitsMetrobusStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.IntegerField()),
                ('position_latitude', models.FloatField()),
                ('position_longitude', models.FloatField()),
                ('date_updated', models.DateTimeField()),
                ('load_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Estado de la unidad',
                'verbose_name_plural': 'Estados de las unidades',
            },
        ),
    ]
