# Generated by Django 3.2.6 on 2022-06-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitsmetrobusstatus',
            name='token',
            field=models.CharField(max_length=500),
        ),
    ]
