# Generated by Django 3.2.6 on 2022-06-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_unitsmetrobusstatus_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestUnitsMetrobusStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('is_completed', models.BooleanField(default=False)),
                ('request_error', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Estado de la peticion',
                'verbose_name_plural': 'Estados del las peticiones',
            },
        ),
    ]
